### ISSUE TITLE
CORs errors on some URLs

### ISSUE THREAD

**Issue by Meikul** [freebee-game/server-backend#2]
It seems like you made a commit specifically to fix this already, but I'm getting CORs errors when I try to fetch from some of the URLs. In fact, all of the URLs fail except for `/cgi-bin/random`. I've tried a few fixes but I think it might be a back end thing. Here's the error I'm getting: 
```
Access to fetch at 'https://freebee.fun/play/today' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
Hope I'm not just doing something wrong. Thanks for making the API available!

**Comment by ibara** [comment]
I may have missed something. I'll check over the next few days. Thanks for the heads up.

**Comment by ibara** [comment]
Hello --

Can you try these two endpoints? If they work, I will drop the `-test` from the two endpoints and update the API documentation accordingly:

https://freebee.fun/cgi-bin/today-test
https://freebee.fun/cgi-bin/yesterday-test

**Comment by Meikul** [comment]
Those both totally work! Are you planning on changing over the date one too?

**Comment by ibara** [comment]
> Those both totally work! Are you planning on changing over the date one too?

Already did. See: https://freebee.fun/api.html

**Comment by Meikul** [comment]
Awesome. Thanks!
