### ISSUE TITLE
The future of Free Bee

### ISSUE THREAD

**Issue by lnicola** [freebee-game/server-backend#3]
Hello!

I read the announcement at https://freebee.fun/shutdown.html. It's bittersweet, but I know how easily doing something you love can turn into a chore.

I'm currently considering forking Free Bee (and so are others, perhaps) in order to keep it alive and even maintained in the future. To expand on that:

 - I have a rough reimplementation of the back-end/API. Yours is under a permissive license, but I'm not too keen on running a CGI service. Mine is made from scratch and unrelated except for the API, which I tried to keep compatible. The most interesting difference is how random games are generated. I'm picking a pangram and a letter from it, instead of generating letters at random and until a good set is found. You'll notice hitting `cgi-bin/random` is a bit faster because of this.
 - I copied the web client (rephrased the footer a little), you can currently find it under https://freebee.dend.ro/play/index.html. The rest of the pages aren't functional since they weren't in the GitHub repo.
 - I'm using your fork of ENABLE, though I don't really like it that much. It feels too hard, and has too many words, e.g. `zouaves`, `shadrach`. I don't currently have a good solution for this.
 - at this moment I'm not interested in manually "curating" the daily games. The first request will pick a random one if it doesn't exist yet (but as long as freebee.fun is running, I'll manually replace them with yours at some point during the day).
 - mine keeps the letters for past games, but not the words; if the dictionary changes, the set of words it returns for a past game changes too. I think I like it better this way.
 - I'd like to add the old games (since `20200728`) -- if you agree to it, especially given the previous point. If you do, you can send me the archive, or I can scrape the API with a reasonable rate limit (should ve less than a thousand requests anyway).
 - I don't know much about web development, but I want to modernize the code a bit, fix the bug causing the yesterday's game not to load on the first try, maybe even change from images to SVG.
 - I don't use the `ncurses` client, but can try to maintaining it, or at least fix any critical issues
 - I haven't decided yet on a new name and domain name
 - I have a VPS and can pay for the domain, but it will probably stop working from time to time (OS updates, deployments etc.). I'm not currently interested in a modern S3/serverless/whatever architecture, which would be more reliable and probably less expensive.
 - I'll publish my code under a permissive open-source license. I go for MIT/Apache-2.0 by default, which should be fine for the back-end, but ISC is okay too. In any case, I'll mention you as the original author.

Are you okay with this arrangement, and do you have any feedback?

Thanks!

**Comment by ibara** [comment]
Hello --

I'd say hold for the moment. I have been doing more thinking and chatting and Free Bee may end up staying.
